# Generated by Django 4.2.2 on 2023-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalURL', models.TextField()),
                ('shortURL', models.TextField(unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('CreatedAT', models.DateTimeField(auto_now=True)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
